#Requires AutoHotkey v2.0
#Include "../core/paths.ahk"
#SingleInstance Force
#Include "../core/hotkeys.ahk"
#Include "../core/modes.ahk"
#Include "record.ahk"

; ═══════════════════════════════════════════════════════════════════════════════
;  tracker.ahk — counts how you work, so the chart has something to draw.
; ───────────────────────────────────────────────────────────────────────────────
;  Six counters, per minute, written through record.ahk:
;
;      keys      every physical key-down
;      chars     the subset that produces a character
;      bksp      Backspace and Delete — the correction/rework signal
;      mouse     button presses, for the mouse-vs-keyboard split
;      active    seconds of the minute you were actually at the machine
;      max.gap   the longest pause that ENDED in this minute, in seconds
;
;  ── It records no text, and cannot ──────────────────────────────────────────
;  The hook is a counter. It is handed a virtual key code, it adds one to a
;  number, and the key code is gone. There is no buffer, no window title and no
;  trigger name anywhere in this file. See record.ahk's header — that is a
;  structural property of the format, not a promise this file makes.
;
;  ── Why MMA's own sends are excluded ────────────────────────────────────────
;  MinSendLevel := 1 makes the hook ignore input generated by Send at the default
;  level, which is every send MMA makes. Without it a mass paste or a hotstring
;  would land in `keys` and `chars`, and the number the whole feature exists to
;  report — how fast YOU type — would rise the more work MMA did for you. The
;  mouse hotkeys below get the same exclusion for free: an AHK hotkey does not
;  fire on its own script's sends.
;
;  ── Idle costs nothing ──────────────────────────────────────────────────────
;  Nothing is written for a minute you were not there. `active` is only bumped on
;  a second where physical idle time is under IdleMs, so leaving MMA running
;  overnight adds no rows at all, and a missing minute reads as zero everywhere
;  downstream. That is what keeps a year of this in the low megabytes.
; ═══════════════════════════════════════════════════════════════════════════════

; The 1s tick is what keeps this alive; Persistent is belt and braces, and cheap.
; (An OnMessage or a hidden Gui would NOT keep a v2 script alive — see the note
; in core/processes.ahk about what does.)
Persistent

CFG := MMA_CFG

; ── tunables ──────────────────────────────────────────────────────────────────
;  IdleMs   how long without physical input before a second stops counting as
;           "active". Two seconds: long enough that reading a fan's message
;           mid-reply is still working time, short enough that a coffee break is
;           not.
;  KeepDays 0 keeps everything forever. This is a log kept in order to spot a
;           pattern across months, so the default does not throw the months away.
IdleMs   := LOG_IniInt(CFG, "Activity", "IdleMs", 2000)
KeepDays := LOG_IniInt(CFG, "Activity", "KeepDays", 0)

; Seed the section so the two knobs are visible to anyone opening the cfg.
if (IniRead(CFG, "Activity", "IdleMs", "") = "") {
    for k, v in Map("IdleMs", IdleMs, "KeepDays", KeepDays)
        try IniWrite(v, CFG, "Activity", k)
}

; ── state ─────────────────────────────────────────────────────────────────────
_actHook    := 0        ; the InputHook doing the counting
_actPeakGap := 0        ; longest idle stretch seen since input last resumed, sec
_actWarned  := false    ; have we already complained about a retained buffer?

; ═══════════════════════════════════════════════════════════════════════════════
;  The keyboard counter
; ═══════════════════════════════════════════════════════════════════════════════

; "V"  — visible: every key still reaches the app you are typing into. This hook
;        observes; it must never be able to swallow a keystroke meant for a chat
;        box.
; "I"  — on {All}: ignore the TEXT the key would contribute, so the hook's own
;        input buffer stays empty. Belt and braces beside the guard in
;        ActTick — the buffer is checked and the hook rebuilt if anything ever
;        does accumulate in it, because "holds a shift's worth of typed messages
;        in memory" is the one failure mode of this feature that actually matters.
; "N"  — notify: call OnKeyDown for each key.
ActStartHook() {
    global _actHook
    try {
        if _actHook
            _actHook.Stop()
    }
    ih := InputHook("V")
    ih.MinSendLevel := 1              ; ignore MMA's own sends — see the header
    ; "I" is the half of this that is an optimisation; "N" is the half the whole
    ; file depends on. If a future AHK stops accepting "I", counting must carry on
    ; rather than the service failing to load — the ActTick guard already handles
    ; a buffer that fills, so the fallback is a real fallback and not a pretence.
    try {
        ih.KeyOpt("{All}", "IN")
    } catch as e {
        LOGW("act.hook", "KeyOpt 'I' was refused, falling back to notify-only —"
                       . " the hook's buffer will be cleared once a second"
                       . " instead (" LOG_Err(e) ")")
        ih.KeyOpt("{All}", "N")
    }
    ih.OnKeyDown := ActKeyDown
    ih.Start()
    _actHook := ih
}

; vk is a virtual key code and nothing else — see the header.
ActKeyDown(ih, vk, sc) {
    ACT_Bump("keys")
    if (vk = 0x08 || vk = 0x2E) {         ; Backspace, Delete
        ACT_Bump("bksp")
        return
    }
    if ActIsChar(vk)
        ACT_Bump("chars")
}

; Does this key produce a character? An approximation, deliberately: the exact
; answer depends on the keyboard layout and on which modifiers are down, and
; getting it exactly right would mean tracking modifier state — which is a
; keylogger's data structure, and this file is not going to have one. The ranges
; below cover the letters, digits, space, the numpad and the OEM punctuation
; keys, which is every key that carries a message.
ActIsChar(vk) {
    if (vk = 0x20)                          ; Space
        return true
    if (vk >= 0x30 && vk <= 0x39)           ; 0-9
        return true
    if (vk >= 0x41 && vk <= 0x5A)           ; A-Z
        return true
    if (vk >= 0x60 && vk <= 0x69)           ; numpad 0-9
        return true
    if (vk >= 0x6A && vk <= 0x6F)           ; numpad * + - . /
        return true
    if (vk >= 0xBA && vk <= 0xC0)           ; ;= ,-. /` and friends
        return true
    if (vk >= 0xDB && vk <= 0xDF)           ; [ \ ] '
        return true
    return false
}

; ═══════════════════════════════════════════════════════════════════════════════
;  The mouse counter
; ───────────────────────────────────────────────────────────────────────────────
;  `~` so the click still reaches the application — same rule as the hook above.
;  `*` so a click with a modifier held is still one click.
;
;  XButton1/XButton2 are also MMA's shared follow-up keys, bound (without `~`) by
;  the engine in another process. Both fire: each process has its own hook, and a
;  blocking hotkey in one does not stop the other's from seeing the press. If
;  that ever changes, the cost is an undercount on two of five buttons — which is
;  why this is `mouse`, one number, rather than a per-button breakdown that would
;  invite reading more into it than it can carry.
; ═══════════════════════════════════════════════════════════════════════════════

ActClick(*) {
    ACT_Bump("mouse")
}

for _actKey in ["~*LButton", "~*RButton", "~*MButton", "~*XButton1", "~*XButton2"] {
    try {
        Hotkey(_actKey, ActClick, "On")
    } catch as e {
        LOGW("act.mouse", "could not bind " _actKey " — mouse clicks will be"
                        . " undercounted (" LOG_Err(e) ")")
    }
}

; ═══════════════════════════════════════════════════════════════════════════════
;  The tick — one second, and it does four things
; ═══════════════════════════════════════════════════════════════════════════════

ActTick() {
    global IdleMs, _actPeakGap, _actHook, _actWarned

    idleSec := A_TimeIdlePhysical // 1000

    if (A_TimeIdlePhysical < IdleMs) {
        ; At the machine. Count the second, and if a pause just ended, write down
        ; how long it was — in the minute it ENDED, which is the minute you would
        ; look at when asking "what happened around then".
        ACT_Bump("active")
        if (_actPeakGap > 0) {
            ACT_Max("max.gap", _actPeakGap)
            _actPeakGap := 0
        }
    } else {
        ; Away. Nothing is written — see the header. Just remember how long for.
        if (idleSec > _actPeakGap)
            _actPeakGap := idleSec
    }

    ; Close off a minute that ended with no further input.
    ACT_FlushIfMinuteEnded()

    ; The guard the "I" option is supposed to make unnecessary. If the hook is
    ; retaining text after all, this notices within a second, says so once, and
    ; rebuilds the hook — so the worst case is one minute of typing held in
    ; memory rather than a whole shift.
    if _actHook {
        try {
            if (StrLen(_actHook.Input) > 0) {
                if !_actWarned {
                    LOGW("act.hook", "the InputHook is retaining typed text despite"
                                   . " KeyOpt 'I' — rebuilding it every time this"
                                   . " happens. Counting is unaffected.")
                    _actWarned := true
                }
                ActStartHook()
            }
        }
    }
}

; ═══════════════════════════════════════════════════════════════════════════════
;  Opening the chart
; ═══════════════════════════════════════════════════════════════════════════════
;  The tracker owns this key rather than the main window, because the key is only
;  worth having when there is data behind it — and the tracker running is exactly
;  the condition for that. Switch the feature off and the key goes with it, which
;  is the honest behaviour: a chart of nothing is not a feature.
ActOpenChart(*) {
    win := MMA_SRC "\ui\activity_window.ahk"
    if !FileExist(win) {
        LOGE("act.chart", "activity_window.ahk is missing — there is no way to see"
                        . " what the tracker has been recording", win)
        return
    }
    ; Flush first. Without this the chart opens showing everything EXCEPT the
    ; minute you are in, which is the minute you pressed the key about.
    ACT_Flush()
    ; Already open: raise it rather than launching a second one. #SingleInstance
    ; Force over there would make the second press close and rebuild the window
    ; you were already reading — same pixels, several seconds later, and your
    ; scroll position gone.
    if WinExist("MMA Activity ahk_class AutoHotkeyGUI") {
        LOGV("act.chart", "already open — raising it")
        WinActivate("MMA Activity ahk_class AutoHotkeyGUI")
        return
    }
    LOGI("act.chart", "opening the activity chart")
    LOG_Try("act.chart", "Run activity_window.ahk", () => Run(win))
}

HK_Bind("gui.activity", ActOpenChart)

; ═══════════════════════════════════════════════════════════════════════════════
;  Boot
; ═══════════════════════════════════════════════════════════════════════════════

ActStartHook()
SetTimer(ActTick, 1000)

; A pending minute must not die with the process — a clean exit through the
; watchdog or through "close all scripts" is the NORMAL way this ends, and losing
; the last minute of every shift would put a notch in the data at exactly the
; time of day you were looking at.
OnExit(ActOnExit)
ActOnExit(reason, code) {
    ACT_Flush()
    return 0
}

ACT_Prune(KeepDays)

LOG_Kv("act.boot", Map("dir",      ACT_DIR,
                       "idleMs",   IdleMs,
                       "keepDays", KeepDays ? KeepDays : "forever",
                       "chartKey", HK_Key("gui.activity")))
